import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
import Heros from '../components/landing/heros'
import Chooseus from '../components/landing/choseuse'
import Product from '../components/landing/products'

export default function Home() {
  return (
    <Layout>
      <>
      <Head>
        <title >Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heros/>
        <Chooseus />
        <Product />
      </main>
      </>
    </Layout>
  )
}
