import Head from 'next/head'
import Layout from '../components/layout'
import Heros from '../components/landing/heros'
import Chooseus from '../components/landing/choseuse'
import Product from '../components/landing/products'
import Testimonial from '../components/landing/testi'
import { getProducts } from "../service/product"
import { getStore } from "../service/store"

export default function Home({products}) {
  console.log(products)
  return (
    <Layout>
      <>
        <Head>
          <title >Blimbing NM</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Heros />
          <Chooseus />
          <Product products={products} />
          <Testimonial />
        </main>
      </>
    </Layout>
  )
}

export async function getServerSideProps(context) {
  const snapshotProducts = await getProducts()
  const snapshotProductsWithOwner = Promise.all(snapshotProducts.docs.map(async (product) => {
    const store = await getStore(product.data().userid)
    const { storename, imagePath } = store.data()
    return {
      id: product.id,
      description: product.data().description,
      name: product.data().name,
      price: product.data().price,
      image: product.data().imagePath,
      store: {
        storename, image: imagePath
      }
    }
  }))
  return {
    props: {
      products: await snapshotProductsWithOwner
    },
  }
}
